services:
  api:
    build:
      context: jamanchu
      dockerfile: Dockerfile_API
    container_name: api
    ports:
      - "8080:8080"
    environment:
      ACTIVE_PROFILE: prod
    restart: always
    networks:
      - jamanchu_network

  batch:
    build:
      context: jamanchu
      dockerfile: Dockerfile_Batch
    container_name: batch
    ports:
      - "8081:8081"
    environment:
      ACTIVE_PROFILE: prod
    restart: always
    networks:
      - jamanchu_network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./data/mysql/env.mysql
    networks:
      - jamanchu_network
    restart: on-failure
  
  npm:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST = mysql
      - DB_MYSQL_PORT =  3306
      - DB_MYSQL_USER = jamanchu
      - DB_MYSQL_PASSWORD = jamanchu
      - DB_MYSQL_NAME = home
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - jamanchu_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: root
    env_file:
      - ./data/grafana/env.grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - jamanchu_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./data/prometheus/config:/etc/prometheus
      - ./data/prometheus/volume:/prometheus
    ports:
      - "9010:9090"
    command:
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: root
    restart: always
    networks:
      - jamanchu_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9111:9100"
    networks:
      - jamanchu_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - prometheus
    restart: always
    networks:
      - jamanchu_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - jamanchu_network
    restart: on-failure

networks:
  jamanchu_network:
    driver: bridge