services:
  api:
    build:
      context: jamanchu
      dockerfile: Dockerfile_API
    container_name: api
    ports:
      - "8080:8080"
    environment:
      ACTIVE_PROFILE: prod
    restart: always
    networks:
      - jamanchu_network

  batch:
    build:
      context: jamanchu
      dockerfile: Dockerfile_Batch
    container_name: batch
    ports:
      - "8081:8081"
    environment:
      ACTIVE_PROFILE: prod
    restart: always
    networks:
      - jamanchu_network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./data/mysql/env.mysql
    networks:
      - jamanchu_network
    restart: on-failure
  
  npm:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST = mysql
      - DB_MYSQL_PORT =  3306
      - DB_MYSQL_USER = jamanchu
      - DB_MYSQL_PASSWORD = jamanchu
      - DB_MYSQL_NAME = home
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - jamanchu_network

networks:
  jamanchu_network:
    driver: bridge